# Generated by Django 4.1.7 on 2023-02-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yrysmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.CharField(blank=True, choices=[('shatura', 'Шатура'), ('ormatek', 'Орматек')], max_length=7),
        ),
    ]
